---
- name: Установка Zabbix Server и Zabbix Web
  hosts: хост
  become: true

  vars:
    zabbix_server_version: "5.4"
    zabbix_web_version: "5.4"
    nginx_version: "latest"
    mysql_version: "latest"
    zabbix_db_name: "zabbix"
    zabbix_db_user: "zabbix"
    zabbix_db_password: "password"

  tasks:
    - name: Установка зависимостей
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - mysql-server
        - mysql-client
        - php-fpm
        - php-mysql
        - php-gd
        - php-ldap
        - php-xml
        - php-mbstring
        - php-bcmath
        - snmp
        - fping

    - name: Установка Zabbix Server
      apt:
        name: "zabbix-server-mysql={{ zabbix_server_version }}"
        state: present

    - name: Установка Zabbix Web
      apt:
        name: "zabbix-web-nginx-mysql={{ zabbix_web_version }}"
        state: present

    - name: Конфигурация MySQL
      mysql_user:
        name: "{{ zabbix_db_user }}"
        password: "{{ zabbix_db_password }}"
        priv: "{{ zabbix_db_name }}.*:ALL"
        host: localhost
        state: present

    - name: Создание базы данных для Zabbix
      mysql_db:
        name: "{{ zabbix_db_name }}"
        state: present

    - name: Импорт схемы базы данных для Zabbix
      shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -u {{ zabbix_db_user }} -p{{ zabbix_db_password }} {{ zabbix_db_name }}
      args:
        executable: /bin/bash

    - name: Конфигурация Zabbix Server
      lineinfile:
        dest: /etc/zabbix/zabbix_server.conf
        regexp: "^DBHost="
        line: "DBHost=localhost"
        state: present

    - name: Конфигурация Zabbix Web
      lineinfile:
        dest: /etc/zabbix/nginx.conf.php
        regexp: "^\\$DB\\['DATABASE'\\] = "
        line: "\\$DB['DATABASE'] = '{{ zabbix_db_name }}';"
        state: present

    - name: Перезапуск сервисов
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - nginx
        - mysql
        - zabbix-server

    - name: Включение автозапуска сервисов
      service:
        name: "{{ item }}"
        enabled: true
      with_items:
        - nginx
        - mysql
        - zabbix-server
